version: '2'

services:
    # web:
    #     build:
    #         context: ./
    #         dockerfile: ./docker/nginx/Dockerfile
    #     image: web/${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    #     ports:
    #         - 9090:80
    #     volumes:
    #         - ./web:/sharetoall/web
    #     depends_on:
    #         - php
    #     environment:
    #         - VIRTUAL_HOST=sharetoall.com www.sharetoall.com
    #         - VIRTUAL_PORT=80

    # php:
    #     build:
    #         context: ./
    #         dockerfile: ./docker/php/Dockerfile-prod
    #     image: php/${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    #     volumes:
    #         - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    #         - ./web:/sharetoall/web
    #         - ./storage:/sharetoall/storage
    #     depends_on:
    #         - redis

    redis:
        build:
            context: ./
            dockerfile: ./docker/redis/Dockerfile
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}-redis:latest
