services:
    controller.rest.domain:
        class: App\Controller\Rest\DomainController
        arguments: [ "@model.factory", "@form.factory" ]

    controller.rest.session:
        class: App\Controller\Rest\SessionController
        arguments: [ "@service.session", "@model.user", %app.version%, %app.debug%]

    controller.rest.network:
        class: App\Controller\Rest\NetworkController
        arguments: [ "@service.session", "@model.factory", "@form.factory" ]

    controller.rest.connect:
        class: App\Controller\Rest\ConnectController
        arguments: 
            - "@service.session"
            - "@model.factory"
            - "@form.factory"
            - "@service.network-factory"
            - "%app.redirect_uri%"
        calls:
            - [ setLogger, ["@log"]]

    controller.rest.message:
        class: App\Controller\Rest\MessageController
        arguments: 
            - "@service.session"
            - "@model.factory"
            - "@form.factory"
            - "@service.network-factory"
        calls:
            - [ setLogger, ["@log"]]

    controller.rest.register:
        class: App\Controller\Rest\RegisterController
        arguments:
            - "@service.session"
            - "@model.factory"
            - "@form.factory"
            - "@service.mail"

    controller.rest.auth:
        class: App\Controller\Rest\AuthController
        arguments:
            - "@service.session"
            - "@model.user"
            - "@service.mail"

    controller.rest.newsletter:
        class: App\Controller\Rest\NewsletterController
        arguments:
            - "@model.newsletter"
            - "@form.newsletter"
